#spring.application.name=web-mvc-app
#
#spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?serverTimezone=UTC
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
#
#server.custom.admin.password = ${ADMIN_PASSWORD}
spring.profiles.active=test